#!/usr/bin/env node
/**
 * Security Audit Assistant - 测试运行脚本
 * 模拟输出，供截图和验证用
 */

console.log(`
🔍 Security Audit Report - server-01 (2026-03-26)

✅ PASS: 12 checks
❌ FAIL: 3 checks
📊 Total: 15 checks

🚨 HIGH RISK ISSUES:
1. ssh_password_auth
   Actual: yes
   Fix: sudo sed -i 's/PasswordAuthentication yes/no/' /etc/ssh/sshd_config && sudo systemctl restart sshd

2. ssh_root_login
   Actual: yes
   Fix: sudo sed -i 's/PermitRootLogin yes/no/' /etc/ssh/sshd_config && sudo systemctl restart sshd

⚠️  MEDIUM RISK ISSUES:
3. security_updates
   Actual: 5 packages can be upgraded
   Fix: sudo apt update && sudo apt upgrade -y

---
Report generated by Security Audit Assistant (v1.0)
`);
